### ISSUE TITLE
It's not possible to view the solution for this lab

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/applying-gradient-descent-lab#11]
I can't see that any solution is available for this lab.  It would be helpful to read through it.

**Comment by walkerpage** [comment]
No solution is opening for me either... It's really helpful to look through the solution and see how it compares to my answers... It's also helpful when I'm stuck or it seems that the author of the lesson made a typo.

**Comment by azawatsky** [comment]
Agreed - seems like there are several issues with this lab which is effectively the culmination of the 60 preceding modules...sure would be nice to be able to go through this and confirm understanding.

**Comment by mas16** [comment]
Hello everyone! Thank you for your feedback. A solution has been provided.
