### ISSUE TITLE
b_gradient and m_gradient expected outputs incorrect?

### ISSUE THREAD

**Issue by walkerpage** [learn-co-curriculum/applying-gradient-descent-lab#13]
In the test for the b_gradient function, `b_gradient(1.79, 0.50, scaled_movies)`, the lab say the expected output is `# 5.37`, but my function returns `19067.4`. I don't understand what could be wrong with the function, and I'm starting to think the lab might simply be mistaken (given all of the other spelling and math typos I've noticed). I've defined the function as follows:
`def b_gradient(m, b, movies):
    return -2 * round(sum(list(map(lambda movie: regression_revenue_error(m, b, movie), movies))), 2)`

The same issue is happening with the m_gradient function. For `m_gradient(1.79, 0.50, scaled_movies)`, the lab says the expected output is `# 2520.59`, but my function returns `8953128.34`. I've defined the function as follows:
`def m_gradient(m, b, movies):
    return -2 * round(sum(list(map(lambda movie: movie['budget_2013$'] * regression_revenue_error(m, b, movie), movies))), 2)`

I don't understand what I'm doing wrong.

**Comment by azawatsky** [comment]
Bump - same issue

**Comment by mas16** [comment]
Hi Everyone! Thank you for letting us know. We have updated the text in the lab to make defining the function more clear. We have also added a solution that can be consulted. Thanks again!
