### ISSUE TITLE
mode = 'lines' not 'line'

### ISSUE THREAD

**Issue by ga12ece** [learn-co-curriculum/applying-gradient-descent-lab#14]
budgets = list(map(lambda movie: movie['budget_2013$'], scaled_movies))
estimated_revenues = list(map(lambda budget: expected_revenue_per_budget(budget), budgets))
len(estimated_revenues)
initial_regression_trace = trace_values(budgets, estimated_revenues, mode = 'lines', name = 'initial regression trace')

**Comment by mas16** [comment]
Hello ga12ece, this has been updated. Thank you for letting us know.
