### ISSUE TITLE
Labs are not saving

### ISSUE THREAD

**Issue by paulinaczheng** [learn-co-curriculum/applying-gradient-descent-lab#3]
I am working on the gradient descent lab and if I leave halfway through, I lose all my work. For some of my prior labs (haven't checked them all), I also can't see my work.

**Comment by PeterBell** [comment]
Hi There, I am sorry to say that there appears to be an intermittent issue where some work is not being saved correctly for some labs. It doesn't happen to all students, so we're currently investigating to try to resolve this as quickly as we can. Sorry about the lost work - I know it can be extremely frustrating. Thanks so much for raising the issue.
