### ISSUE TITLE
mode = line error again

### ISSUE THREAD

**Issue by htalasan** [learn-co-curriculum/applying-gradient-descent-lab#7]
it's lines

**Comment by UpwardTrajectory** [comment]
add this line:
`consultant_estimated_revenues_trace.update({'mode':'lines'})`  
right before the final line, so it looks like this:  
`consultant_estimated_revenues_trace.update({'mode':'lines'})`
`plot([revenues_per_budgets_trace, consultant_estimated_revenues_trace], revenues_layout)`

**Comment by mcarlisle** [comment]
bump - multiple locations

**Comment by mrodzlgd** [comment]
This problem is in most of the trace definitions for this lab. Just make sure that in any trace definition you have mode: 'lines' instead of 'line'

**Comment by mrodzlgd** [comment]
> bump - multiple locations

This problem is in most of the trace definitions for this lab. Just make sure that in any trace definition you have mode: 'lines' instead of 'line'

**Comment by isobeldaley** [comment]
Sill not fixed - bump

**Comment by mas16** [comment]
Hello everyone, this has been corrected. Thanks for letting us know!
