### ISSUE TITLE
i think the formulae is wrong

### ISSUE THREAD

**Issue by htalasan** [learn-co-curriculum/applying-gradient-descent-lab#8]
the formulas for J/db and J/dm, I think, are wrong...

**Comment by mcarlisle** [comment]
The lab text is misleading, telling the student to compute the gradients with a coefficient of -2 instead of the scaled version (-1/n) given in the previous lesson, applying-gradient-descent. The commented answers for b_gradient and m_gradient are computed using -1/n.

**Comment by isobeldaley** [comment]
I agree with the above.  When will a fix be implemented?

**Comment by caitsnyder** [comment]
Still not resolved

**Comment by mas16** [comment]
Thank you everyone for letting us know! We have updated the formulas.
